---
- hosts: all
  become: true

  pre_tasks:

    - name: "Install custom facts"
      include_role:
        name: facts

    - name: "Ensure dependencies are installed"
      package:
        name:
          - sudo
          - openssh-server
        state: present

  tasks:

    - name: Basic setup
      include_role:
        name: base
      vars:
        system:
          hostname: homeserver
          admin:
            username: carsten
            key: https://github.com/cadimmek.keys
            #            dotfiles: https://github.com/cadimmek/dotfiles.git
            passwordless_sudo: true
            groups:
              - adm
              - dialout
              - cdrom
              - sudo
              - audio
              - video
              - plugdev
              - games
              - users
              - input
              - netdev
              - gpio
              - i2c
              - spi
              - docker

          packages:
            - git
            - nano
            - dnsutils

          ufw:
            rules:
              - {rule: "allow", port: "80", proto: "tcp"}
              - {rule: "allow", port: "443", proto: "tcp"}
      tags: ['always']

    - name: Install docker
      include_role:
        name: docker
      vars:
        docker:
          users:
            - carsten
          pip_executable: pip3


