---
- hosts: all
  become: true

  pre_tasks:

    - name: "Install custom facts"
      include_role:
        name: facts

    - name: "Ensure dependencies are installed"
      package:
        name:
          - sudo
          - openssh-server
        state: present

  tasks:

    - name: Basic setup
      include_role:
        name: base
      vars:
        system:
          hostname: homeserver
          admin:
            username: carsten
            key: https://github.com/cadimmek.keys
            passwordless_sudo: true
          packages:
            - git
            - nano
          ufw:
            rules:
              - {rule: "allow", port: "80", proto: "tcp"}
              - {rule: "allow", port: "443", proto: "tcp"}
          mounts:
            tmpfs:
              - { src: "/run", size: "10%", options: "nodev,noexec,nosuid" }
              - { src: "/tmp", size: "10%", options: "nodev,nosuid" }
              - { src: "/var/log", size: "10%", options: "nodev,noexec,nosuid" }
      tags: ['always']



    - name: Install docker
      include_role:
        name: docker
      vars:
        docker:
          users:
            - carsten

    - name: Install pi-hole
      include_role:
        name: pihole

    - name: Install homeassistant
      include_role:
        name: homeassistant

