---
- name: "Create user"
  user:
    name: "{{ user.username }}"
    shell: "{{ user.shell }}"

- name: "Create groups"
  group:
    name: "{{item}}"
    state: present
  with_items: "{{user.groups}}"
  when: user.groups|length > 0

- name: "Add user to groups"
  user:
    name: "{{ user.username }}"
    append: yes
    group: "{{item}}"
  with_items: "{{user.groups}}"
  when: user.groups|length > 0

- name: "Enable including files from sudoers.d/"
  lineinfile:
    path: "/etc/sudoers"
    regexp: "^#includedir /etc/sudoers.d"
    line: "#includedir /etc/sudoers.d"
    state: "present"
    backup: True

- name: "Enable passwordless sudo"
  copy:
    content: "%{{ user.username }} ALL=(ALL) NOPASSWD:ALL"
    dest: "/etc/sudoers.d/{{ user.username }}"
    owner: "root"
    group: "root"
    mode: "0440"
    validate: 'visudo -cf %s'
  when: user.passwordless_sudo

- name: "Set authorized_key to allow SSH key based logins"
  authorized_key:
    user: "{{ user.username }}"
    key: "{{  user.ssh_key }}"
    state: present
  when: user.ssh_key | default(False)
