---
docker:
  pip_executable: pip
  apt:
    release_channel: stable
    arch: amd64
    repository: "deb [arch={{ docker.apt.arch }}] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} {{ docker.apt.release_channel }}"
    ignore_key_error: true
  compose:
    version: 1.25.3
    install: true
