---
- name: Updating hostname {{ system.hostname }}
  block:
    - hostname:
        name: "{{ system.hostname }}"
      register: hostname_change

    - copy:
        content: "{{ system.hostname }}{{'\n'}}"
        dest: /etc/hostname
        backup: true
      register: hostname_change

- name: Update /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1'
    line: "127.0.0.1{{'\t'}}{{ system.hostname }}"
    backup: true
    state: present
