---
- name: Set timezone to {{ system.timezone }}
  timezone:
    name: "{{ system.timezone }}"
  when: system.timezome is defined
  notify:
    - update-timezone

- name: Ensure locale {{ system.locale }} exists
  locale_gen:
    name: "{{ system.locale }}"
    state: present
  when: system.locale is defined
  notify:
    - update-locale

- name: Set default system locale
  debconf:
    name: 'locales'
    question: 'locales/default_environment_locale'
    vtype: 'string'
    value: '{{ system.locale }}'
  when: system.locale is defined
  notify:
    - update-locale
