---

- name: Mount tmpfs
  mount:
    src: tmpfs
    name: "{{ item.src }}"
    fstype: tmpfs
    opts: "defaults,{{ item.options }},size={{ item.size }}"
    dump: "0"
    passno: "0"
    state: mounted
  with_items: "{{ system.mounts.tmpfs }}"
  when: system.mounts.tmpfs|length > 0

