---
- name: Install ufw
  apt:
    package: ufw
    state: present

- name: Configure ufw defaults
  ufw:
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
  with_items:
    - { direction: "incoming", policy: "deny" }
    - { direction: "outgoing", policy: "allow" }
  when: merged.ufw.rules|length > 0
  notify:
    - reload ufw

- name: Always allow ssh to make sure ansible works
  ufw:
    rule: "allow"
    port: "22"
    proto: "tcp"

- name: "Allow IGMP: {{ merged.ufw.allow_igmp }}"
  blockinfile:
    dest: /etc/ufw/before.rules
    insertbefore: ^# don't delete the 'COMMIT' line or these rules won't be processed
    block: |
      # allow IGMP
      -A ufw-before-input -p igmp -d 224.0.0.0/4 -j ACCEPT
      -A ufw-before-output -p igmp -d 224.0.0.0/4 -j ACCEPT
    state: present
  when: merged.ufw.allow_igmp|bool
  notify:
    - reload ufw

- name: Configure ufw rules
  ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    from_ip: "{{ item.from_ip|default('any') }}"
  with_items:
    - "{{ merged.ufw.rules }}"
  when: merged.ufw.rules|length > 0
  notify:
    - reload ufw

- name: Enable ufw
  ufw:
    state: enabled
