---
- name: Install unattended-upgrades
  package:
    name: unattended-upgrades
    state: present

- name: Create apt auto-upgrades configuration
  template:
    src: 20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: 0644

- name: Create apt unattended-upgrades configuration
  template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: 0644
