---
- include_vars: vault.yml

- name: Clone repository
  git:
    repo: "https://github.com/cadimmek/pi-hole.git"
    dest: "{{pihole.install_dir}}"
    force: yes

- name: Setup firewall
  ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    from_ip: "{{ item.from_ip|default('any') }}"
  with_items:
    - {rule: "allow", port: "53", proto: "tcp"}

- name: Create environment file
  template:
    src: .env
    dest: "{{pihole.install_dir}}"

- name: Start service
  docker_compose:
    project_src: "{{pihole.install_dir}}"
    state: present
